local phrases = {
    "NO BAN 1Day",
    "NO BAN 3Day",
    "NO BAN 7Day",
    "NO BAN 14Day",
    "NO BAN 30Day",
    "NO BAN 60Day",
    "NO BAN 90Day",
    "NO BAN 24H",
    "NO BAN 48H",
    "NO BAN 72H",

    "NO BAN VIP 1Day",
    "NO BAN VIP 3Day",
    "NO BAN VIP 7Day",
    "NO BAN VIP 14Day",
    "NO BAN VIP 30Day",

    "NO BAN PRO 1Day",
    "NO BAN PRO 3Day",
    "NO BAN PRO 7Day",
    "NO BAN PRO 14Day",
    "NO BAN PRO 30Day",

    "NO BAN SAFE 1Day",
    "NO BAN SAFE 3Day",
    "NO BAN SAFE 7Day",
    "NO BAN SAFE 14Day",
    "NO BAN SAFE 30Day",

    "NO PAND 1Day",
    "NO PAND 3Day",
    "NO PAND 7Day",
    "NO PAND 14Day",
    "NO PAND 30Day",

    "BAN SAFE 1Day",
    "BAN SAFE 3Day",
    "BAN SAFE 7Day",
    "BAN SAFE 14Day",
    "BAN SAFE 30Day",

    "VIP SAFE 1Day",
    "VIP SAFE 3Day",
    "VIP SAFE 7Day",
    "VIP SAFE 14Day",
    "VIP SAFE 30Day",

    "SAFE MOD 1Day",
    "SAFE MOD 3Day",
    "SAFE MOD 7Day",
    "SAFE MOD 14Day",
    "SAFE MOD 30Day",

    "PRO SAFE 1Day",
    "PRO SAFE 3Day",
    "PRO SAFE 7Day",
    "PRO SAFE 14Day",
    "PRO SAFE 30Day",

    "PREMIUM SAFE 1Day",
    "PREMIUM SAFE 3Day",
    "PREMIUM SAFE 7Day",
    "PREMIUM SAFE 14Day",
    "PREMIUM SAFE 30Day",

    "ANTI BAN 1Day",
    "ANTI BAN 3Day",
    "ANTI BAN 7Day",
    "ANTI BAN 14Day",
    "ANTI BAN 30Day",

    "VIP ACCESS 1Day",
    "VIP ACCESS 3Day",
    "VIP ACCESS 7Day",
    "VIP ACCESS 14Day",
    "VIP ACCESS 30Day",

    "PRO ACCESS 1Day",
    "PRO ACCESS 3Day",
    "PRO ACCESS 7Day",
    "PRO ACCESS 14Day",
    "PRO ACCESS 30Day",

    "PREMIUM ACCESS 1Day",
    "PREMIUM ACCESS 3Day",
    "PREMIUM ACCESS 7Day",
    "PREMIUM ACCESS 14Day",
    "PREMIUM ACCESS 30Day",

    "SAFE MODE 1Day",
    "SAFE MODE 3Day",
    "SAFE MODE 7Day",
    "SAFE MODE 14Day",
    "SAFE MODE 30Day",

    "VIP MODE 1Day",
    "VIP MODE 3Day",
    "VIP MODE 7Day",
    "VIP MODE 14Day",
    "VIP MODE 30Day"
    "NO BAN ULTRA 1Day",
    "NO BAN ULTRA 3Day",
    "NO BAN ULTRA 7Day",
    "NO BAN ULTRA 14Day",
    "NO BAN ULTRA 30Day",
    "NO BAN PLUS 1Day",
    "NO BAN PLUS 3Day",
    "NO BAN PLUS 7Day",
    "NO BAN PLUS 14Day",
    "NO BAN PLUS 30Day",
    "NO BAN PREMIUM 1Day",
    "NO BAN PREMIUM 3Day",
    "NO BAN PREMIUM 7Day",
    "NO BAN PREMIUM 14Day",
    "NO BAN PREMIUM 30Day",
    "NO BAN ACCESS 1Day",
    "NO BAN ACCESS 3Day",
    "NO BAN ACCESS 7Day",
    "NO BAN ACCESS 14Day",
    "NO BAN ACCESS 30Day",

    "BAN PRO 1Day",
    "BAN PRO 3Day",
    "BAN PRO 7Day",
    "BAN PRO 14Day",
    "BAN PRO 30Day",
    "BAN PREMIUM 1Day",
    "BAN PREMIUM 3Day",
    "BAN PREMIUM 7Day",
    "BAN PREMIUM 14Day",
    "BAN PREMIUM 30Day",
    "BAN VIP 1Day",
    "BAN VIP 3Day",
    "BAN VIP 7Day",
    "BAN VIP 14Day",
    "BAN VIP 30Day",

    "SAFE PRO 1Day",
    "SAFE PRO 3Day",
    "SAFE PRO 7Day",
    "SAFE PRO 14Day",
    "SAFE PRO 30Day",
    "SAFE PREMIUM 1Day",
    "SAFE PREMIUM 3Day",
    "SAFE PREMIUM 7Day",
    "SAFE PREMIUM 14Day",
    "SAFE PREMIUM 30Day",
    "SAFE ULTRA 1Day",
    "SAFE ULTRA 3Day",
    "SAFE ULTRA 7Day",
    "SAFE ULTRA 14Day",
    "SAFE ULTRA 30Day",

    "VIP MOD 1Day",
    "VIP MOD 3Day",
    "VIP MOD 7Day",
    "VIP MOD 14Day",
    "VIP MOD 30Day",
    "PRO MOD 1Day",
    "PRO MOD 3Day",
    "PRO MOD 7Day",
    "PRO MOD 14Day",
    "PRO MOD 30Day",
    "PREMIUM MOD 1Day",
    "PREMIUM MOD 3Day",
    "PREMIUM MOD 7Day",
    "PREMIUM MOD 14Day",
    "PREMIUM MOD 30Day",

    "VIP PACK 1Day",
    "VIP PACK 3Day",
    "VIP PACK 7Day",
    "VIP PACK 14Day",
    "VIP PACK 30Day",
    "PRO PACK 1Day",
    "PRO PACK 3Day",
    "PRO PACK 7Day",
    "PRO PACK 14Day",
    "PRO PACK 30Day",
    "PREMIUM PACK 1Day",
    "PREMIUM PACK 3Day",
    "PREMIUM PACK 7Day",
    "PREMIUM PACK 14Day",
    "PREMIUM PACK 30Day",
    "VIP EDITION 1Day",
    "VIP EDITION 3Day",
    "VIP EDITION 7Day",
    "VIP EDITION 14Day",
    "VIP EDITION 30Day",
    "PRO EDITION 1Day",
    "PRO EDITION 3Day",
    "PRO EDITION 7Day",
    "PRO EDITION 14Day",
    "PRO EDITION 30Day",
    "SAFE EDITION 1Day",
    "SAFE EDITION 3Day",
    "SAFE EDITION 7Day",
    "SAFE EDITION 14Day",
    "SAFE EDITION 30Day"
    
local phrases = {
    "No Monitoring",
    "No Detection",
    "No Tracking",
    "No Logging",
    "No Scanning",
    "No Checking",
    "No Verification",
    "No Analysis",
    "No Reporting",
    "No Alerts",
    "No Warning",
    "No Restriction",
    "No Block",
    "No Control",
    "No Inspection",
    "No Recording",
    "No Tracking Log",
    "No Data Log",
    "No Activity Log",
    "No Security Check",
    "No File Check",
    "No Code Check",
    "No Integrity Check",
    "No Background Check",
    "No Status Check",
    "No Session Check",
    "No Device Check",
    "No Network Check",
    "No Process Check",
    "No Runtime Check",
    "No Module Check",
    "No Package Check",
    "No Memory Check",
    "No System Check",
    "No Access Check",
    "No Permission Check",
    "No Connection Check",
    "No Update Check",
    "No Version Check",
    "No Server Check",
    "No Client Check",
    "No Event Log",
    "No Debug Log",
    "No Error Log",
    "No Report",
    "No Scan",
    "No Monitor",
    "No Tracker",
    "No Logger",
    "No Scanner"
}

local testPhrases = {
    "No Anti-Fraud",
    "No Anti-Cheat",
    "No Security",
    "No Protection",
    "No Detection",
    "No Monitoring",
    "No Tracking",
    "No Verification",
    "No Validation",
    "No Integrity Check",
    "No Security Check",
    "No Fraud Check",
    "No Risk Check",
    "No Threat Check",
    "No Account Check",
    "No Device Check",
    "No Session Check",
    "No Login Check",
    "No Network Check",
    "No Server Check",
    "No Client Check",
    "No File Check",
    "No Memory Check",
    "No Process Check",
    "No Runtime Check",
    "No Code Check",
    "No Module Check",
    "No Package Check",
    "No Activity Check",
    "No Behavior Check",
    "No Anomaly Check",
    "No Suspicious Activity",
    "No Fraud Detection",
    "No Cheat Detection",
    "No Security Scan",
    "No Fraud Scan",
    "No Account Monitoring",
    "No Device Monitoring",
    "No Session Monitoring",
    "No Activity Monitoring"
}

local protectionTests2 = {
    "No Anti-Exploit",
    "No Anti-Abuse",
    "No Anti-Bot",
    "No Anti-Spam",
    "No Anti-Clone",
    "No Anti-Spoof",
    "No Anti-Injection",
    "No Anti-Hook",
    "No Anti-Dump",
    "No Anti-Modification",
    "No Tamper Detection",
    "No Debug Detection",
    "No Hook Detection",
    "No Injection Detection",
    "No Dump Detection",
    "No Modification Detection",
    "No Environment Validation",
    "No Hardware Validation",
    "No Software Validation",
    "No Client Validation",
    "No Host Validation",
    "No Connection Validation",
    "No Certificate Validation",
    "No Encryption Check",
    "No Secure Storage",
    "No Key Validation",
    "No Session Security",
    "No Account Validation",
    "No Identity Check",
    "No User Verification",
    "No Login Security",
    "No Credential Check",
    "No Token Check",
    "No API Security",
    "No Request Check",
    "No Response Check",
    "No Packet Validation",
    "No Network Validation",
    "No Connection Check",
    "No Server
    
local protectionTests3 = {
    "No Security Validation",
    "No Security Monitoring",
    "No Security Logging",
    "No Security Reporting",
    "No Security Alerts",
    "No Security Events",
    "No Threat Detection",
    "No Threat Monitoring",
    "No Threat Analysis",
    "No Threat Validation",
    "No Risk Detection",
    "No Risk Analysis",
    "No Risk Monitoring",
    "No Fraud Monitoring",
    "No Fraud Analysis",
    "No Fraud Reporting",
    "No Cheat Monitoring",
    "No Cheat Analysis",
    "No Cheat Reporting",
    "No Exploit Detection",
    "No Exploit Monitoring",
    "No Abuse Detection",
    "No Abuse Monitoring",
    "No Bot Detection",
    "No Bot Monitoring",
    "No Automation Detection",
    "No Automation Monitoring",
    "No Spoof Detection",
    "No Spoof Monitoring",
    "No Clone Detection",
    "No Clone Monitoring",
    "No Tamper Monitoring",
    "No Tamper Reporting",
    "No Debug Monitoring",
    "No Debug Reporting",
    "No Hook Monitoring",
    "No Hook Reporting",
    "No Injection Monitoring",
    "No Injection Reporting",
    "No Memory Monitoring",
    "No Memory Analysis",
    "No Process Monitoring",
    "No Process Analysis",
    "No Runtime Monitoring",
    "No Runtime Analysis",
    "No File Monitoring",
    "No File Analysis",
    "No Asset Monitoring",
    "No Asset Analysis",
    "No Package Monitoring",
    "No Package Analysis"
}

local testPhrases = {
    "No Ban On Closing The Game",
    "No Ban On Exiting The Game",
    "No Ban On Restarting The Game",
    "No Ban On Reopening The Game",
    "No Ban On Leaving The Game",
    "No Ban On Game Exit",
    "No Ban On Game Restart",
    "No Ban On App Exit",
    "No Ban On App Restart",
    "No Ban On Force Closing",
    "No Ban On Reconnect",
    "No Ban On Disconnect",
    "No Ban On Session End",
    "No Ban On Session Restart",
    "No Ban On Login Again"
}

    "No Ban After Game Close",
    "No Ban After Game Exit",
    "No Ban After App Close",
    "No Ban After App Exit",
    "No Ban After Restart",
    "No Ban After Reconnect",
    "No Ban After Disconnect",
    "No Ban After Session End",
    "No Ban After Session Reset",
    "No Ban On Reconnect",
    "No Ban On Disconnect",
    "No Ban On Rejoin",
    "No Ban On Relogin",
    "No Ban On Restart",
    "No Ban On Reopen",
    "No Ban On App Restart",
    "No Ban On Game Restart",
    "No Ban On Session Reset",
    "No Ban On Network Change",
    "No Ban On Connection Loss",
    "No Ban On Internet Loss",
    "No Ban On Background Mode",
    "No Ban On App Background",
    "No Ban On Game Background",
    "No Ban On Screen Lock",
    "No Ban On Screen Unlock",
    "No Ban On Device Restart",
    "No Ban On Device Reboot",
    "No Ban On Account Relogin",
    "No Ban On Session Reconnect"